[workspace]
resolver = "2"

members = [
    "src/client",
    "src/sc_plugin",
    "src/server",
    "src/shared",
]

[patch.crates-io]
audiopus_sys = { git = "https://github.com/sevenc-nanashi/audiopus_sys", rev = "00e9d16" }
